development:
  adapter: postgresql
  encoding: unicode
  database: mystore_development
  pool: 5
  username: timwilliams
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: mystore_test
  pool: 5
  username: timwilliams
  password: 
